#!/bin/sh

APPID=org.webosinternals.purple
APPS=/media/cryptofs/apps

# Set Application Install Directory
APPDIR=${APPS}/usr/palm/applications/${APPID}

VALIDATOR=${APPID}.validator
TRANSPORT=${APPID}.transport

#Kill transport if it's running
killall ${TRANSPORT} || true

#Kill validator if it's running
killall ${VALIDATOR} || true

# Remove old service files
rm /etc/palm/db/kinds/org.webosinternals.*.purple
rm /etc/palm/db/kinds/org.webosinternals.purple.config
rm /etc/palm/tempdb/kinds/org.webosinternals.*.purple

# Copy service files
cp -r ${APPDIR}/system/var/ /
cp -r ${APPDIR}/system/etc/ /

mkdir -p /var/preferences/${APPID}/transport
mkdir -p /var/preferences/${APPID}/validator
mkdir -p /var/preferences/${APPID}/certificates
ln -s ../certificates /var/preferences/${APPID}/transport
ln -s ../certificates /var/preferences/${APPID}/validator

# Set execute on services
chmod 755 /var/usr/sbin/${VALIDATOR}
chmod 755 /var/usr/sbin/${TRANSPORT}

# Rescan services
/usr/bin/ls-control scan-services || true

# Rescan Luna (Makes plugins show and work correctly)
luna-send -n 1 palm://com.palm.applicationManager/rescan {} || true

# Create org.webosinternals.purple.config kind
# luna-send -a org.webosinternals.purple.transport -n 1 palm://com.palm.db/putKind "$(cat /etc/palm/db/kinds/org.webosinternals.purple.config)"

# We are done
exit 0
