#!/bin/sh

APPID=org.webosinternals.purple
APPS=/media/cryptofs/apps

# Set Application Install Directory
APPDIR=${APPS}/usr/palm/applications/${APPID}

VALIDATOR=${PACKAGE}.validator
TRANSPORT=${PACKAGE}.transport

#Kill transport if it's running
killall ${TRANSPORT} || true

#Kill validator if it's running
killall ${VALIDATOR} || true

# Copy service files
cp -r ${APPDIR}/system/var/ /
cp -r ${APPDIR}/system/etc/ /

mkdir -p /var/preferences/${APPID}

# Set execute on services
chmod 755 /var/usr/sbin/${VALIDATOR}
chmod 755 /var/usr/sbin/${TRANSPORT}

# Rescan services
/usr/bin/ls-control scan-services || true

# Rescan Luna (Makes plugins show and work correctly)
luna-send -n 1 palm://com.palm.applicationManager/rescan {} || true

# We are done
exit 0
