#!/bin/sh

APPID=org.webosinternals.purple
APPS=/media/cryptofs/apps

VALIDATOR=${APPID}.validator
TRANSPORT=${APPID}.transport

APPDIR=${APPS}/usr/palm/applications/${APPID}

#Kill transport if it's running
killall ${TRANSPORT} || true

#Kill validator if it's running
killall ${VALIDATOR} || true

# Cleanup roles
rm -f /var/palm/ls2/roles/prv/${VALIDATOR}.json
rm -f /var/palm/ls2/roles/prv/${TRANSPORT}.json

rm -f /var/palm/ls2/roles/pub/${VALIDATOR}.json
rm -f /var/palm/ls2/roles/pub/${TRANSPORT}.json

# Cleanup System Services
rm -f /var/usr/sbin/${VALIDATOR}
rm -f /var/usr/sbin/${TRANSPORT}
rm -f /var/usr/lib/libpurple.so
rm -f /var/palm/system-services/${VALIDATOR}.json
rm -f /var/palm/system-services/${TRANSPORT}.json

# Cleanup DB files
rm -f -r /etc/palm/activities/${APPID}
rm -f /etc/palm/tempdb/kinds/org.webosinternals.*.purple
rm -f /etc/palm/db/kinds/org.webosinternals.*.purple
rm -f /etc/palm/db/kinds/${TRANSPORT}.account
rm -f /etc/palm/db/permissions/org.webosinternals.*.purple
rm -f /etc/palm/db/permissions/${TRANSPORT}.account

# Cleanup Accounts
rm -f -r ${APPS}/usr/palm/accounts/${APPID}.*

# Cleanup Application
rm -f -r ${APPDIR}

# We are done
exit 0
