#!/bin/sh

APPID=org.webosinternals.purple
APPS=/media/cryptofs/apps

# Set Application Install Directory
APPDIR=${APPS}/usr/palm/applications/${APPID}

#Kill org.webosinternals.imlibpurpletransport if it's running
killall -HUP grep ${APPID}.transport || true
killall -HUP grep ${APPID}.transport || true
killall -HUP grep ${APPID}.transport || true

#Kill org.webosinternals.imaccountvalidator if it's running
killall -HUP grep ${APPID}.validator || true
killall -HUP grep ${APPID}.validator || true
killall -HUP grep ${APPID}.validator || true

# Copy service files
cp -r ${APPDIR}/files/var/ /
cp -r ${APPDIR}/files/etc/ /

# Set execute on services
chmod 755 /var/usr/sbin/${APPID}.validator
chmod 755 /var/usr/sbin/${APPID}.transport

# Rescan services
/usr/bin/ls-control scan-services || true

# Rescan Luna (Makes plugins show and work correctly)
luna-send -n 1 palm://com.palm.applicationManager/rescan {} || true

# We are done
exit 0
